"""drop owner_type and add signals_json

Revision ID: 5435152bc2bb
Revises: 20260303_0003
Create Date: 2026-03-16 16:10:58.230609

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "5435152bc2bb"
down_revision: Union[str, Sequence[str], None] = "20260303_0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ux_candidates_external_id_not_null"),
        table_name="candidates",
        postgresql_where="(external_id IS NOT NULL)",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_emb_hnsw_job_posting_1536_c60cde78"),
        table_name="embeddings",
        postgresql_ops={"(vector::vector(1536))": "vector_cosine_ops"},
        postgresql_using="hnsw",
        postgresql_where="(((model)::text = 'openai/text-embedding-3-small'::text) AND (dimensions = 1536) AND ((owner_type)::text = 'job_posting'::text))",
        if_exists=True,
    )
    op.drop_index(
        op.f("ix_emb_hnsw_resume_section_1536_c60cde78"),
        table_name="embeddings",
        postgresql_ops={"(vector::vector(1536))": "vector_cosine_ops"},
        postgresql_using="hnsw",
        postgresql_where="(((model)::text = 'openai/text-embedding-3-small'::text) AND (dimensions = 1536) AND ((owner_type)::text = 'resume_section'::text))",
        if_exists=True,
    )
    op.drop_index(op.f("ix_embeddings_owner_type"), table_name="embeddings", if_exists=True)
    op.drop_index(
        op.f("ix_embeddings_model_dimensions_owner"), table_name="embeddings", if_exists=True
    )
    op.create_index(
        "ix_embeddings_model_dimensions_owner",
        "embeddings",
        ["model", "dimensions", "owner_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_embeddings_owner"), table_name="embeddings", if_exists=True)
    op.create_index("ix_embeddings_owner", "embeddings", ["owner_id"], unique=False)
    op.drop_column("embeddings", "owner_type")
    op.add_column(
        "resumes", sa.Column("signals_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resumes", "signals_json")
    op.add_column(
        "embeddings",
        sa.Column("owner_type", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    )
    op.drop_index("ix_embeddings_owner", table_name="embeddings")
    op.create_index(
        op.f("ix_embeddings_owner"), "embeddings", ["owner_type", "owner_id"], unique=False
    )
    op.drop_index("ix_embeddings_model_dimensions_owner", table_name="embeddings")
    op.create_index(
        op.f("ix_embeddings_model_dimensions_owner"),
        "embeddings",
        ["model", "dimensions", "owner_type", "owner_id"],
        unique=False,
    )
    op.create_index(op.f("ix_embeddings_owner_type"), "embeddings", ["owner_type"], unique=False)
    op.create_index(
        op.f("ix_emb_hnsw_resume_section_1536_c60cde78"),
        "embeddings",
        [sa.literal_column("(vector::vector(1536))")],
        unique=False,
        postgresql_ops={"(vector::vector(1536))": "vector_cosine_ops"},
        postgresql_using="hnsw",
        postgresql_where="(((model)::text = 'openai/text-embedding-3-small'::text) AND (dimensions = 1536) AND ((owner_type)::text = 'resume_section'::text))",
    )
    op.create_index(
        op.f("ix_emb_hnsw_job_posting_1536_c60cde78"),
        "embeddings",
        [sa.literal_column("(vector::vector(1536))")],
        unique=False,
        postgresql_ops={"(vector::vector(1536))": "vector_cosine_ops"},
        postgresql_using="hnsw",
        postgresql_where="(((model)::text = 'openai/text-embedding-3-small'::text) AND (dimensions = 1536) AND ((owner_type)::text = 'job_posting'::text))",
    )
    op.create_index(
        op.f("ux_candidates_external_id_not_null"),
        "candidates",
        ["external_id"],
        unique=True,
        postgresql_where="(external_id IS NOT NULL)",
    )
    # ### end Alembic commands ###
