"""add interview_pack_json to matches

Revision ID: 8f12b4f1d4a9
Revises: 5435152bc2bb
Create Date: 2026-04-07 14:57:34.961057

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "8f12b4f1d4a9"
down_revision: Union[str, Sequence[str], None] = "5435152bc2bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matches",
        sa.Column("interview_pack_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "interview_pack_json")
    # ### end Alembic commands ###
