"""add_async_task_model

Revision ID: f2ca03afb3a7
Revises: 8f12b4f1d4a9
Create Date: 2026-04-07 18:30:56.817752

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "f2ca03afb3a7"
down_revision: Union[str, Sequence[str], None] = "8f12b4f1d4a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "async_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_type", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("input_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_async_tasks_status"), "async_tasks", ["status"], unique=False)
    op.create_index(op.f("ix_async_tasks_task_type"), "async_tasks", ["task_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_async_tasks_task_type"), table_name="async_tasks")
    op.drop_index(op.f("ix_async_tasks_status"), table_name="async_tasks")
    op.drop_table("async_tasks")
    # ### end Alembic commands ###
