summarizer_default:
  default_model: ollama/llama3.2:3b
  default_litellm_params:
    temperature: 0.2
    max_tokens: 900
  fallbacks:
    - model: openai/gpt-4o-mini
      litellm_params:
        temperature: 0.2
        max_tokens: 900
  fallback_policy:
    num_retries: 2

extractor_default:
  default_model: ollama/llama3.2:3b
  default_litellm_params:
    temperature: 0.0
    max_tokens: 1200
  fallbacks:
      - model: openai/gpt-4o-mini
        litellm_params:
          temperature: 0.2
          max_tokens: 900
  fallback_policy:
    num_retries: 2

explainer_default:
  default_model: ollama/llama3.2:3b
  default_litellm_params:
    temperature: 0.1
    max_tokens: 1200
  fallbacks:
      - model: openai/gpt-4o-mini
        litellm_params:
          temperature: 0.2
          max_tokens: 900
  fallback_policy:
    num_retries: 2

embedding_default:
  default_model: ollama/embeddinggemma
  default_litellm_params: {}
  fallbacks:
    - model: openai/text-embedding-3-small
      litellm_params: {}
  fallback_policy:
    num_retries: 1
